-- ==========================================
-- 1. リセット処理 (既存のテーブルがあれば削除)
-- ==========================================
DROP TABLE IF EXISTS directmessages CASCADE;
DROP TABLE IF EXISTS ranking_results CASCADE;
DROP TABLE IF EXISTS follows CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS replies CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS weekly_themes CASCADE;
DROP TABLE IF EXISTS topic_master CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ==========================================
-- 2. テーブル作成 (箱を作る)
-- ==========================================

-- ユーザー
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    profile_text TEXT,
    favorite_id BIGINT,
    icon_index INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ジャンルマスタ
CREATE TABLE genres (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL
);

-- お題トピックマスタ
CREATE TABLE topic_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theme_name TEXT NOT NULL
);

-- 週替わりお題管理
CREATE TABLE weekly_themes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT REFERENCES topic_master(id),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL
);

-- 投稿
CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    ruby_content JSONB, 
    genre_id INTEGER,
    weekly_theme_id BIGINT REFERENCES weekly_themes(id),
    likes_num INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- リプライ
CREATE TABLE replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- いいね（いとをかし）
CREATE TABLE likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, post_id)
);

-- フォロー
CREATE TABLE follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    followed_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(follower_id, followed_id)
);

-- ランキング結果
CREATE TABLE ranking_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weekly_theme_id BIGINT REFERENCES weekly_themes(id),
    post_id BIGINT REFERENCES posts(id),
    rank INTEGER,
    fixed_likes_count INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ダイレクトメッセージ
CREATE TABLE directmessages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    receiver_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    reply_77 BOOLEAN DEFAULT FALSE,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 3. 初期データ投入 (中身を入れる)
-- ==========================================

-- ジャンルデータ (IDを固定して挿入)
INSERT INTO genres (id, name) VALUES
(1, '春'),
(2, '夏'),
(3, '秋'),
(4, '冬'),
(5, '趣味'),
(6, '食べ物'),
(7, '学校'),
(8, 'その他');

-- お題データ
INSERT INTO topic_master (theme_name) VALUES
('春の訪れ'), ('リモートワーク'), ('推し活'), ('ダイエット'),
('夏の思い出'), ('年末年始'), ('バレンタイン'), ('新生活'),
('春'), ('夏'), ('秋'), ('冬'), 
('猫'), ('推し'), ('卒業'), 
('早起き'), ('忘れ物'), ('二度寝'), ('掃除'), ('ゴミ出し'), ('お風呂'), ('テレビ'), ('コンビニ'),
('残業'), ('上司'), ('給料日'), ('通勤電車'), ('会議'), ('リモートワーク'), ('有給休暇'), ('挨拶'),
('ダイエット'), ('筋肉痛'), ('健康診断'), ('白髪'), ('物忘れ'), ('サプリメント'), ('運動'), ('老眼'),
('夫婦喧嘩'), ('お弁当'), ('反抗期'), ('孫'), ('ペット（犬・猫）'), ('里帰り'), ('ママ友・飲み仲間'), ('初恋'),
('へそくり'), ('衝動買い'), ('値上げ'), ('特売・セール'), ('宝くじ'), ('お小遣い'), ('ポイントカード'),
('お正月'), ('桜（花見）'), ('猛暑'), ('ラーメン'), ('ビール'), ('スイーツ'), ('推し活'), 
('スマホ'), ('SNS'), ('パスワード'), ('AI（人工知能）'), ('Wi-Fi'), 
('秘密'), ('言い訳'), ('夜食');

-- 今週のお題データ作成
-- ※アプリを開いた時に必ず「開催中のお題」があるように、日付を自動計算しています
INSERT INTO weekly_themes (topic_id, start_date, end_date)
VALUES
-- 今開催中のお題（今日を含める）
(1, CURRENT_DATE - INTERVAL '3 days', CURRENT_DATE + INTERVAL '4 days'),
-- 先週のお題（ランキング表示用）
(2, CURRENT_DATE - INTERVAL '10 days', CURRENT_DATE - INTERVAL '4 days');